---
- name: Configure
  hosts: gitlab.fiipractic.lan
  become: yes
  tasks:
  
    - name: Set EXTERNAL_URL
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: '^external_url'
        line: 'external_url "https://gitlab.fiipractic.lan"'

    - name: Restart
      systemd:
        name: gitlab-runsvdir
        state: restarted